//! Build-time code generator for the OSI converter plugin.
//! (owner: `feature/converter` session)
//!
//! Strategy (see docs plan): drive the vendored `protoc` to emit a
//! `FileDescriptorSet` for the two OSI streams (GroundTruth + HostVehicleData)
//! with `--include_imports`, decode it with `prost-types`, then walk every
//! message / field / enum and emit a typed Godot `Resource` class plus a pure
//! `convert_*` free function per message.
//!
//! Mapping convention (REQUIREMENTS.md §5, "A" geometry policy — raw mirror):
//! the generated `Resource` keeps the *raw* OSI values 1:1 with the proto;
//! coordinate conversion (§3) lives in the hand-written `converter::coords`
//! module, not here. So this generator is purely structural and never reorders
//! or transforms axes.

use std::collections::HashMap;
use std::path::PathBuf;
use std::process::Command;

use prost::Message;
use prost_types::field_descriptor_proto::{Label, Type};
use prost_types::{DescriptorProto, FieldDescriptorProto, FileDescriptorSet};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    // <repo>/crates/godot-osi -> up twice to repo root.
    let repo_root = manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("manifest dir has a grandparent")
        .to_path_buf();
    let proto_root = repo_root.join("proto");
    let osi3 = proto_root.join("osi3");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let fds_path = out_dir.join("osi_fds.bin");

    // 1. Emit a FileDescriptorSet for the two streams + all transitive imports.
    let protoc = protoc_bin_vendored::protoc_bin_path().expect("vendored protoc binary");
    let status = Command::new(&protoc)
        .arg(format!("--proto_path={}", proto_root.display()))
        .arg(format!("--proto_path={}", osi3.display()))
        .arg("--include_imports")
        .arg(format!("--descriptor_set_out={}", fds_path.display()))
        .arg(osi3.join("osi_groundtruth.proto"))
        .arg(osi3.join("osi_hostvehicledata.proto"))
        .status()
        .expect("failed to run protoc");
    assert!(status.success(), "protoc failed to emit descriptor set");

    // 2. Decode it.
    let bytes = std::fs::read(&fds_path).expect("read descriptor set");
    let fds = FileDescriptorSet::decode(bytes.as_slice()).expect("decode descriptor set");

    // 3. First pass: register every message (recursively) so message-typed
    //    fields can resolve their Godot class name and prost path.
    let mut reg = Registry::default();
    for file in &fds.file {
        let package = file.package.as_deref().unwrap_or("");
        for msg in &file.message_type {
            reg.collect(package, &[], msg);
        }
    }

    // 4. Second pass: generate Rust for every osi3 message.
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    for file in &fds.file {
        // Only generate for the OSI core package; service/well-known are skipped.
        if file.package.as_deref() != Some("osi3") {
            continue;
        }
        for msg in &file.message_type {
            gen_message(&mut out, "osi3", &[], msg, &reg);
        }
    }

    let generated = out_dir.join("osi_generated.rs");
    std::fs::write(&generated, out).expect("write generated source");

    // 5. Emit a human/AI-readable schema doc for the distribution package. It is
    //    built from the same `Registry` that drives codegen, so the doc can never
    //    drift from the actually-generated `Osi*` classes. Written into the source
    //    tree (gitignored) so CI can copy it into the addon; content-guarded so a
    //    no-op rebuild doesn't touch the mtime or dirty the working tree.
    let schema = gen_schema_md(&fds, &reg);
    let schema_dir = repo_root.join("packaging").join("generated");
    let schema_path = schema_dir.join("SCHEMA.md");
    let unchanged = std::fs::read_to_string(&schema_path)
        .map(|existing| existing == schema)
        .unwrap_or(false);
    if !unchanged {
        std::fs::create_dir_all(&schema_dir).expect("create packaging/generated dir");
        std::fs::write(&schema_path, schema).expect("write SCHEMA.md");
    }

    println!("cargo:rerun-if-changed={}", proto_root.display());
    println!("cargo:rerun-if-changed=build.rs");
}

// NOTE: no inner `#![..]` attribute here — this text is `include!`d into the
// `converter::generated` module, where inner attributes would be illegal. The
// lint allows live on that module instead (see converter/generated.rs).
const GENERATED_HEADER: &str = "// @generated by build.rs (feature/converter). Do not edit.\n\
    // Typed Godot `Resource` mirror of the ASAM OSI v3.7.0 schema (raw values).\n\
    use godot::prelude::*;\n\
    use osi_types::osi3;\n\n";

/// Metadata about one proto message needed to reference it from a field.
struct MsgInfo {
    /// Godot class name, e.g. `OsiMovingObjectVehicleClassification`.
    godot_name: String,
    /// prost path, e.g. `osi3::moving_object::VehicleClassification`.
    prost_path: String,
    /// convert fn name, e.g. `convert_moving_object_vehicle_classification`.
    convert_fn: String,
}

#[derive(Default)]
struct Registry {
    /// Fully-qualified proto name (no leading dot), e.g. `osi3.MovingObject`.
    by_fq: HashMap<String, MsgInfo>,
}

impl Registry {
    /// Recursively record `msg` and its nested messages.
    /// `pascal_path` is the chain of message names from the package root.
    fn collect(&mut self, package: &str, pascal_path: &[String], msg: &DescriptorProto) {
        let name = msg.name().to_string();
        let mut path = pascal_path.to_vec();
        path.push(name.clone());

        let fq = if package.is_empty() {
            path.join(".")
        } else {
            format!("{}.{}", package, path.join("."))
        };

        let godot_name = format!("Osi{}", path.iter().map(|s| pascal(s)).collect::<String>());
        // prost path: package as base module, ancestors as snake_case modules,
        // leaf as the PascalCase struct name.
        let mut prost_path = String::from("osi3");
        for (i, seg) in path.iter().enumerate() {
            if i + 1 == path.len() {
                prost_path.push_str("::");
                prost_path.push_str(&pascal(seg));
            } else {
                prost_path.push_str("::");
                prost_path.push_str(&snake(seg));
            }
        }
        let convert_fn = format!("convert_{}", path.iter().map(|s| snake(s)).collect::<Vec<_>>().join("_"));

        self.by_fq.insert(
            fq,
            MsgInfo {
                godot_name,
                prost_path,
                convert_fn,
            },
        );

        for nested in &msg.nested_type {
            self.collect(package, &path, nested);
        }
    }

    fn get(&self, fq_with_dot: &str) -> &MsgInfo {
        let key = fq_with_dot.trim_start_matches('.');
        self.by_fq
            .get(key)
            .unwrap_or_else(|| panic!("unknown message type referenced: {key}"))
    }
}

/// Emit the struct + convert fn for `msg`, then recurse into nested messages.
fn gen_message(
    out: &mut String,
    package: &str,
    pascal_path: &[String],
    msg: &DescriptorProto,
    reg: &Registry,
) {
    let mut path = pascal_path.to_vec();
    path.push(msg.name().to_string());
    let fq = format!("{}.{}", package, path.join("."));
    let info = reg.get(&fq);

    // --- struct definition ---
    out.push_str("#[derive(GodotClass)]\n#[class(base=Resource, init)]\npub struct ");
    out.push_str(&info.godot_name);
    out.push_str(" {\n");
    for field in &msg.field {
        if field.oneof_index.is_some() {
            // OSI v3.7.0 has no oneofs; if upstream adds one, skip with a note
            // rather than emitting broken code.
            out.push_str(&format!(
                "    // skipped oneof member: {}\n",
                field.name()
            ));
            continue;
        }
        let gty = godot_field_type(field, reg);
        out.push_str(&format!("    #[var]\n    pub {}: {},\n", godot_ident(field), gty));
    }
    out.push_str("}\n\n");

    // --- convert fn ---
    out.push_str(&format!(
        "pub fn {}(src: &{}) -> Gd<{}> {{\n    Gd::from_object({} {{\n",
        info.convert_fn, info.prost_path, info.godot_name, info.godot_name
    ));
    for field in &msg.field {
        if field.oneof_index.is_some() {
            continue;
        }
        let expr = convert_expr(field, reg);
        out.push_str(&format!("        {}: {},\n", godot_ident(field), expr));
    }
    out.push_str("    })\n}\n\n");

    for nested in &msg.nested_type {
        gen_message(out, package, &path, nested, reg);
    }
}

/// Build the Markdown schema reference for every generated `Osi*` class.
///
/// Driven by the same `Registry`/descriptor walk as the codegen above, so the
/// listed classes and field types are exactly what ends up in the binary. Output
/// is sorted by Godot class name for a stable, diff-friendly file.
fn gen_schema_md(fds: &FileDescriptorSet, reg: &Registry) -> String {
    // Collect (godot_name, proto_fq, fields) for every osi3 message, recursively.
    let mut classes: Vec<SchemaClass> = Vec::new();
    for file in &fds.file {
        if file.package.as_deref() != Some("osi3") {
            continue;
        }
        for msg in &file.message_type {
            collect_schema(&mut classes, "osi3", &[], msg, reg);
        }
    }
    classes.sort_by(|a, b| a.godot_name.cmp(&b.godot_name));

    let mut out = String::new();
    out.push_str(
        "# OSI Resource Schema Reference\n\n\
         > **Auto-generated — do not edit.** Produced by `crates/godot-osi/build.rs` from the\n\
         > ASAM OSI v3.7.0 `.proto` schema, in lockstep with the actual generated classes.\n\n\
         The `godot-osi` addon converts each incoming OSI frame into typed Godot `Resource`\n\
         objects — one `Resource` class per OSI message. `OsiConverter` emits the two top-level\n\
         snapshots, `OsiGroundTruth` and `OsiHostVehicleData`; every nested message below is\n\
         reachable through their fields.\n\n\
         ## Conventions\n\n\
         - **Class naming**: proto `osi3.MovingObject` → Godot class `OsiMovingObject`; nested\n\
         messages flatten with their parent, e.g. `osi3.MovingObject.VehicleClassification` →\n\
         `OsiMovingObjectVehicleClassification`.\n\
         - **Raw values**: these Resources mirror the proto values **1:1** with *no* coordinate\n\
         transform. OSI is right-handed Z-up; convert to Godot's left-handed Y-up via the\n\
         helper nodes (`OsiMovingObjectSpawner` / `OsiMovingObjectVisualizer`) or your own code.\n\
         - **Field types**: nested messages are `Option<Gd<Osi…>>` (null when unset); `repeated`\n\
         fields become packed/typed arrays. `enum` and `uint64` are exposed as `i64` (Godot has\n\
         no native u64; the OSI \"invalid id\" sentinel `MAX(uint64)` therefore reads as `-1`).\n\
         - Field **semantics** (units, meaning, validity rules) are documented in the bundled\n\
         proto sources under `third_party/osi3/*.proto`.\n\n",
    );
    out.push_str(&format!("**{} generated classes.**\n\n---\n\n", classes.len()));

    for c in &classes {
        out.push_str(&format!("### {}\n\n", c.godot_name));
        out.push_str(&format!("Proto: `{}`\n\n", c.proto_fq));
        if c.fields.is_empty() {
            out.push_str("_(no fields)_\n\n");
            continue;
        }
        out.push_str("| Field | Type | Repeated |\n|---|---|---|\n");
        for f in &c.fields {
            out.push_str(&format!(
                "| `{}` | {} | {} |\n",
                f.name,
                f.ty,
                if f.repeated { "yes" } else { "" }
            ));
        }
        out.push('\n');
    }
    out
}

struct SchemaClass {
    godot_name: String,
    proto_fq: String,
    fields: Vec<SchemaField>,
}

struct SchemaField {
    name: String,
    /// Godot `#[var]` type, code-wrapped for Markdown.
    ty: String,
    repeated: bool,
}

fn collect_schema(
    classes: &mut Vec<SchemaClass>,
    package: &str,
    pascal_path: &[String],
    msg: &DescriptorProto,
    reg: &Registry,
) {
    let mut path = pascal_path.to_vec();
    path.push(msg.name().to_string());
    let fq = format!("{}.{}", package, path.join("."));
    let info = reg.get(&fq);

    let mut fields = Vec::new();
    for field in &msg.field {
        if field.oneof_index.is_some() {
            continue;
        }
        // Code-wrapped so the `<Gd<…>>` angle brackets render literally (and are
        // not parsed as HTML) in Markdown table cells. Same type string the
        // `#[var]` actually gets — see `godot_field_type`.
        fields.push(SchemaField {
            name: godot_ident(field),
            ty: format!("`{}`", godot_field_type(field, reg)),
            repeated: field.label() == Label::Repeated,
        });
    }

    classes.push(SchemaClass {
        godot_name: info.godot_name.clone(),
        proto_fq: fq,
        fields,
    });

    for nested in &msg.nested_type {
        collect_schema(classes, package, &path, nested, reg);
    }
}

/// The Godot field type for `#[var]`.
fn godot_field_type(field: &FieldDescriptorProto, reg: &Registry) -> String {
    let repeated = field.label() == Label::Repeated;
    let ty = field.r#type();
    if repeated {
        match ty {
            Type::Double => "PackedFloat64Array".into(),
            Type::Float => "PackedFloat32Array".into(),
            Type::Int32 | Type::Sint32 | Type::Sfixed32 | Type::Enum => "PackedInt32Array".into(),
            Type::Int64 | Type::Sint64 | Type::Sfixed64 => "PackedInt64Array".into(),
            Type::Uint32 | Type::Fixed32 | Type::Uint64 | Type::Fixed64 | Type::Bool => {
                "Array<i64>".into()
            }
            Type::String => "PackedStringArray".into(),
            Type::Bytes => "Array<PackedByteArray>".into(),
            Type::Message => {
                let m = reg.get(field.type_name());
                format!("Array<Gd<{}>>", m.godot_name)
            }
            Type::Group => "Array<i64>".into(), // unsupported; OSI has none
        }
    } else {
        match ty {
            Type::Double => "f64".into(),
            Type::Float => "f32".into(),
            Type::Int32 | Type::Sint32 | Type::Sfixed32 => "i32".into(),
            Type::Int64 | Type::Sint64 | Type::Sfixed64 => "i64".into(),
            Type::Uint32 | Type::Fixed32 => "u32".into(),
            // Godot ints are i64; uint64 (e.g. Identifier.value) is cast. The
            // OSI sentinel MAX(uint64) "invalid id" therefore reads as -1.
            Type::Uint64 | Type::Fixed64 => "i64".into(),
            Type::Bool => "bool".into(),
            Type::String => "GString".into(),
            Type::Bytes => "PackedByteArray".into(),
            Type::Enum => "i64".into(),
            Type::Message => {
                let m = reg.get(field.type_name());
                format!("Option<Gd<{}>>", m.godot_name)
            }
            Type::Group => "i64".into(),
        }
    }
}

/// The expression building the Godot value from `src.<field>`.
fn convert_expr(field: &FieldDescriptorProto, reg: &Registry) -> String {
    // Read from the prost source using prost's identifier (keywords -> `r#name`).
    let name = field_ident(field);
    let access = format!("src.{name}");
    let repeated = field.label() == Label::Repeated;
    let ty = field.r#type();

    if repeated {
        match ty {
            Type::Double => format!("PackedFloat64Array::from({access}.as_slice())"),
            Type::Float => format!("PackedFloat32Array::from({access}.as_slice())"),
            Type::Int32 | Type::Sint32 | Type::Sfixed32 | Type::Enum => {
                format!("PackedInt32Array::from({access}.as_slice())")
            }
            Type::Int64 | Type::Sint64 | Type::Sfixed64 => {
                format!("PackedInt64Array::from({access}.as_slice())")
            }
            Type::Uint32 | Type::Fixed32 | Type::Uint64 | Type::Fixed64 | Type::Bool => {
                format!("{{ let mut a = Array::<i64>::new(); for v in &{access} {{ a.push(*v as i64); }} a }}")
            }
            Type::String => {
                format!("{{ let mut a = PackedStringArray::new(); for v in &{access} {{ a.push(v); }} a }}")
            }
            Type::Bytes => format!(
                "{{ let mut a = Array::<PackedByteArray>::new(); for v in &{access} {{ a.push(&PackedByteArray::from(v.as_slice())); }} a }}"
            ),
            Type::Message => {
                let m = reg.get(field.type_name());
                format!(
                    "{{ let mut a = Array::<Gd<{g}>>::new(); for v in &{access} {{ a.push(&{c}(v)); }} a }}",
                    g = m.godot_name,
                    c = m.convert_fn
                )
            }
            Type::Group => "Array::<i64>::new()".into(),
        }
    } else {
        match ty {
            Type::Double | Type::Float => format!("{access}.unwrap_or_default()"),
            Type::Int32 | Type::Sint32 | Type::Sfixed32 | Type::Int64 | Type::Sint64
            | Type::Sfixed64 | Type::Uint32 | Type::Fixed32 | Type::Bool => {
                format!("{access}.unwrap_or_default()")
            }
            Type::Uint64 | Type::Fixed64 => format!("{access}.unwrap_or_default() as i64"),
            Type::Enum => format!("{access}.unwrap_or_default() as i64"),
            Type::String => format!("GString::from({access}.as_deref().unwrap_or_default())"),
            Type::Bytes => {
                format!("PackedByteArray::from({access}.clone().unwrap_or_default().as_slice())")
            }
            Type::Message => {
                let m = reg.get(field.type_name());
                format!("{access}.as_ref().map(|v| {}(v))", m.convert_fn)
            }
            Type::Group => "0i64".into(),
        }
    }
}

/// Identifier for reading the prost source field, raw-escaping Rust keywords
/// exactly like prost does (`type` -> `r#type`).
fn field_ident(field: &FieldDescriptorProto) -> String {
    let name = field.name();
    if is_rust_keyword(name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

/// Identifier for our generated struct field. `#[var]` cannot use raw idents
/// (gdext would build an invalid getter like `get_r#type`), so keyword names
/// get a trailing underscore instead (`type` -> `type_`).
fn godot_ident(field: &FieldDescriptorProto) -> String {
    let name = field.name();
    if is_rust_keyword(name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

fn is_rust_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "break" | "const" | "continue" | "crate" | "else" | "enum" | "extern" | "false"
            | "fn" | "for" | "if" | "impl" | "in" | "let" | "loop" | "match" | "mod" | "move"
            | "mut" | "pub" | "ref" | "return" | "self" | "Self" | "static" | "struct" | "super"
            | "trait" | "true" | "type" | "unsafe" | "use" | "where" | "while" | "async"
            | "await" | "dyn" | "abstract" | "become" | "box" | "do" | "final" | "macro"
            | "override" | "priv" | "typeof" | "unsized" | "virtual" | "yield" | "try"
    )
}

/// snake_case a proto identifier (already snake in OSI, but be safe).
fn snake(s: &str) -> String {
    let mut out = String::new();
    let mut prev_lower = false;
    for ch in s.chars() {
        if ch.is_uppercase() {
            if prev_lower {
                out.push('_');
            }
            out.extend(ch.to_lowercase());
            prev_lower = false;
        } else {
            out.push(ch);
            prev_lower = ch.is_lowercase() || ch.is_numeric();
        }
    }
    out
}

/// UpperCamelCase a proto identifier, matching prost/heck normalization so the
/// generated prost paths line up (e.g. `ColorRGB` -> `ColorRgb`,
/// `ColorRGBIR` -> `ColorRgbir`). We normalize through snake_case first, which
/// lowercases acronym runs, then title-case each word.
fn pascal(s: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for ch in snake(s).chars() {
        if ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}
